### ISSUE TITLE
There is no Android Launcher in the portal

### ISSUE THREAD

**Issue by vaztimur** [fiskaltrust/middleware-demo-android#1]
Hello,
yesterday i received the email about the release of the android launcher. Unfortunately I cannot see it in the portal to download it. Just in the sandbox portal, but in the production. Do i something missing here?

Is it only Android 7 compatible? Because our cash systems are running on Android 5, so is there an possibitlity to make the launcher backwards compatible?

**Comment by TSchmiedlechner** [comment]
Hello @vaztimur,
thanks for reaching out! The Android Launcher is currently only available on the sandbox because we are trying to collect feedback from users before pushing it to the production Portal, but we'll enable it there as soon as possible.

Regarding Android 5: I think re-targeting to Android 5 would be technically possible, but require some additional work. Could you please reach out to sales@fiskaltrust.de with some details about your scenario to help us prioritize this?

Thanks!
Tom

**Comment by TSchmiedlechner** [comment]
Closing this now, as the Android Launcher is available in production for quite some time now. Thank you very much for your questions 🙂
